# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='imagedata',
            name='number',
        ),
        migrations.AddField(
            model_name='imagedata',
            name='sample_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ImageSample'),
        ),
    ]
