# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170309_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='imagesample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imagesample',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
