# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170309_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagedata',
            old_name='level_type',
            new_name='gray_scale_level',
        ),
        migrations.RenameField(
            model_name='imagedata',
            old_name='resolution_type',
            new_name='resolution_level',
        ),
    ]
