# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170310_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesample',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
