# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_imagesample_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesample',
            name='serial',
            field=models.IntegerField(default=0),
        ),
    ]
